// Forward declarations for java.awt
#pragma once


namespace java
{
    namespace awt
    {
        class AWTEvent;
        class AWTEventMulticaster;
        class AWTKeyStroke;
        class AttributeValue;
        class BufferCapabilities;
        class BufferCapabilities_FlipContents;
        class Button;
        class Canvas;
        class Checkbox;
        class CheckboxMenuItem;
        class Choice;
        class Color;
        class Component;
        class ComponentOrientation;
        class Component_AWTTreeLock;
        class Component_AccessibleAWTComponent;
        class Component_AccessibleAWTComponent_AccessibleAWTComponentHandler;
        class Component_AccessibleAWTComponent_AccessibleAWTFocusHandler;
        class Component_BaselineResizeBehavior;
        class Component_BltBufferStrategy;
        class Component_BltSubRegionBufferStrategy;
        class Component_DummyRequestFocusController;
        class Component_FlipBufferStrategy;
        class Component_FlipSubRegionBufferStrategy;
        class Component_ProxyCapabilities;
        class Component_SingleBufferStrategy;
        struct Composite;
        class Container;
        class Container_AccessibleAWTContainer;
        class Container_AccessibleAWTContainer_AccessibleContainerHandler;
        class Container_DropTargetEventTargetFilter;
        struct Container_EventTargetFilter;
        class Container_MouseEventTargetFilter;
        class Container_WakingRunnable;
        class Cursor;
        class Desktop;
        class Dialog;
        class Dialog_ModalExclusionType;
        class Dialog_ModalityType;
        class Dimension;
        class Event;
        class EventQueue;
        class FileDialog;
        class FocusManager;
        class FocusTraversalPolicy;
        class Font;
        class FontMetrics;
        class Font_FontAccessImpl;
        class Frame;
        class Frame_AccessibleAWTFrame;
        class Graphics;
        class Graphics2D;
        class GraphicsConfiguration;
        class Image;
        class ImageCapabilities;
        class Insets;
        class JobAttributes;
        class Label;
        struct LayoutManager;
        class LightweightDispatcher;
        class List;
        class Menu;
        class MenuBar;
        class MenuComponent;
        struct MenuContainer;
        class MenuItem;
        class PageAttributes;
        struct Paint;
        struct PaintContext;
        class Panel;
        class Point;
        class PointerInfo;
        class Polygon;
        class PopupMenu;
        class PrintJob;
        class Rectangle;
        class RenderingHints;
        class RenderingHints_Key;
        class ScrollPane;
        class Scrollbar;
        struct Shape;
        struct Stroke;
        class TextArea;
        class TextField;
        class Toolkit;
        class Toolkit_DesktopPropertyChangeSupport;
        class Toolkit_SelectiveAWTEventListener;
        class Toolkit_ToolkitEventMulticaster;
        struct Transparency;
        class Window;
        class Window_AccessibleAWTWindow;
        class Window_Type;
        class Window_WindowDisposerRecord;
    } // awt
} // java
